program: /home/chntzi001/deepEEG/EEGPT/downstream/run_class_finetuning_EEGPT_change_age.py
method: grid
metric:
  goal: maximize
  name: accuracy
parameters:
  layer_decay:
    values: [0.65, 0.75, 0.85, 0.95]
  weight_decay:
    values: [0.01, 0.05, 0.1]
