program: /home/chntzi001/deepEEG/EEGPT/pretrain/ss/run_pretraining.py
project: ss_deepEEG
method: grid
metric:
  goal: minimize
  name: loss
parameters:
  lr:
    values: [0.000045, 0.00005, 0.00004, 0.000055, 0.00006]
  batch_size:
    values: [32, 64]
