program: /home/chntzi001/deepEEG/EEGPT/downstream/run_class_finetuning_EEGPT_change_age.py
method: grid
metric:
  goal: maximize
  name: accuracy
parameters:
  lr:
    values: [0.00001, 0.00002, 0.00003, 0.00004]
  batch_size:
    values: [128, 256]
